export default [
    {
        title: 'ID',
        dataIndex: 'id',
        key: 'id',
        ellipsis: true,
        align: 'center',
        width: 80
    },
    {
        title: '标题',
        dataIndex: 'title',
        key: 'title',
        ellipsis: true,
        align: 'center',
    },
    {
        title: '用户ID',
        dataIndex: 'user_id',
        key: 'user_id',
        align: 'center',
        ellipsis: true,
    },
    {
        title: '栏目id',
        dataIndex: 'channel_id',
        key: 'channel_id',
        ellipsis: true,
        align: 'center',
    },
    {
        title: '图片',
        dataIndex: 'image',
        key: 'image',
        ellipsis: true,
        align: 'center',
        slots: { customRender: 'image' },
    },
    {
        title: '描述',
        dataIndex: 'describe',
        key: 'describe',
        ellipsis: true,
        align: 'center',
        slots: { customRender: 'describe' },
    },
    {
        title: '浏览次数',
        dataIndex: 'views',
        key: 'views',
        ellipsis: true,
        align: 'center',
        width: 100,
    },
    {
        title: '点赞次数',
        dataIndex: 'likes',
        key: 'likes',
        ellipsis: true,
        align: 'center',
        width: 100,
    },
    {
        title: '游客访问',
        dataIndex: 'is_guest',
        key: 'is_guest',
        ellipsis: true,
        align: 'center',
        width: 100,
        customRender: (item: any) => {
            return item.text ? '是' : '否'
        },
    },
    {
        title: '是否评论',
        dataIndex: 'is_comment',
        key: 'is_comment',
        ellipsis: true,
        align: 'center',
        width: 100,
        customRender: (item: any) => {
            return item.text ? '是' : '否'
        },
    },
    {
        title: '热度',
        dataIndex: 'flag',
        key: 'flag',
        ellipsis: true,
        align: 'center',
        width: 100,
    },
    {
        title: '创建时间',
        dataIndex: 'createTime',
        key: 'createTime',
        align: 'center',
        ellipsis: true,
        width: 200,
    },
    {
        title: '操作',
        key: 'action',
        align: 'center',
        width: 200,
        slots: { customRender: 'action' },
    },
]
