export default [
    {
        title: 'ID',
        dataIndex: 'id',
        key: 'id',
        ellipsis: true,
        align: 'center',
        width: 80,
    },
    {
        title: '标题',
        dataIndex: 'title',
        key: 'title',
        ellipsis: true,
        align: 'center',
        formData: {
            name: 'title',
            label: '标题',
            element: 'a-input',
            props: {
                placeholder: '输入标题',
            },
        },
        formSearch: {
            name: 'title',
            label: '标题',
            element: 'a-input',
            props: {
                placeholder: '输入标题搜索',
                value: '',
            },
        },
    },
    {
        title: '用户ID',
        dataIndex: 'user_id',
        key: 'user_id',
        align: 'center',
        ellipsis: true,
        formData: {
            name: 'user_id',
            label: '用户ID',
            element: 'a-input',
            props: {
                placeholder: '用户ID',
            },
        },
        formSearch: {
            name: 'user_id',
            label: '用户ID',
            element: 'a-input',
            props: {
                placeholder: '输入用户ID搜索',
                value: '',
            },
        },
    },
    {
        title: '标题样式',
        dataIndex: 'title_style',
        key: 'title_style',
        ellipsis: true,
        align: 'center',
        visible: false,
        formData: {
            name: 'title_style',
            label: '标题样式',
            element: 'a-textarea',
            props: {
                placeholder: '输入标题样式',
                maxlength: 300,
            },
        },
    },
    {
        title: '栏目ID',
        dataIndex: 'channel_id',
        key: 'channel_id',
        ellipsis: true,
        align: 'center',
        formData: {
            name: 'channel_id',
            label: '栏目ID',
            element: 'a-input',
            props: {
                placeholder: '栏目ID',
            },
        },
    },
    {
        title: '热度',
        dataIndex: 'flag',
        key: 'flag',
        ellipsis: true,
        align: 'center',
        width: 100,
        visible: false,
        formData: {
            name: 'flag',
            label: '热度',
            element: 'a-select',
            options: [{ name: '置顶', value: '置顶' }, { name: '最新', value: '最新' }, {
                name: '推荐', value: '推荐',
            }, { name: '热门', value: '热门' }],
            props: {
                placeholder: '选择热度',
            },
        },
        formSearch: {
            name: 'flag',
            label: '热度',
            element: 'a-input',
            props: {
                placeholder: '输入热度搜索',
                value: '',
            },
        },
    },
    {
        title: '关键词',
        dataIndex: 'keywords',
        key: 'keywords',
        ellipsis: true,
        align: 'center',
        width: 100,
        visible: false,
        formData: {
            name: 'keywords',
            label: '关键词',
            element: 'a-select',
            options: [],
            props: {
                placeholder: '选择关键词',
            },
        },
    },
    {
        title: '封面图',
        dataIndex: 'image',
        key: 'image',
        ellipsis: true,
        align: 'center',
        slots: { customRender: 'image' },
        formData: {
            name: 'image',
            label: '封面图',
            element: 'bag-upload-image',
            props: {
                placeholder: '上传封面图',
                isFileMore: false,
            },
        },
    },
    {
        title: '组图',
        dataIndex: 'images',
        key: 'images',
        ellipsis: true,
        align: 'center',
        slots: { customRender: 'images' },
        formData: {
            name: 'images',
            label: '组图',
            element: 'bag-upload-image',
            props: {
                placeholder: '上传组图',
            },
        },
    },
    {
        title: '内容简述',
        dataIndex: 'describe',
        key: 'describe',
        ellipsis: true,
        align: 'center',
        visible: false,
        formData: {
            name: 'describe',
            label: '内容简述',
            element: 'a-textarea',
            props: {
                placeholder: '输入内容简述',
                maxlength: 300,
            },
        },
    },
    {
        title: '内容',
        dataIndex: 'content',
        key: 'content',
        ellipsis: true,
        align: 'center',
        visible: false,
        layout: {
            xs: 24,
            sm: 24,
            md: 24,
            lg: 24,
            xl: 24,
        },
        formData: {
            name: 'content',
            label: '内容',
            element: 'md-editor',
            autoLink: false,
            labelCol: {
                span: 2,
                offset: 0,
            },
            wrapperCol: {
                span: 21,
                offset: 0,
            },
            props: {
                placeholder: '输入内容',
                previewTheme: 'mk-cute',
                codeTheme: 'paraiso',
                fileSize: 1000,
            },
        },
    },
    {
        title: '浏览次数',
        dataIndex: 'views',
        key: 'views',
        ellipsis: true,
        align: 'center',
        width: 100,
        formData: {
            name: 'views',
            label: '浏览次数',
            element: 'a-input',
            props: {
                placeholder: '输入浏览次数',
            },
        },
    },
    {
        title: '点赞次数',
        dataIndex: 'likes',
        key: 'likes',
        ellipsis: true,
        align: 'center',
        width: 100,
        formData: {
            name: 'likes',
            label: '点赞次数',
            element: 'a-input',
            props: {
                placeholder: '输入点赞次数',
            },
        },
    },
    {
        title: '评论数量',
        dataIndex: 'comments',
        key: 'comments',
        ellipsis: true,
        align: 'center',
        width: 100,
        visible: false,
        formData: {
            name: 'comments',
            label: '评论数量',
            element: 'a-input',
            props: {
                placeholder: '输入评论数量',
            },
        },
    },
    {
        title: '游客访问',
        dataIndex: 'is_guest',
        key: 'is_guest',
        ellipsis: true,
        align: 'center',
        width: 100,
        customRender: (item: any) => {
            return item.text ? '是' : '否'
        },
        formData: {
            name: 'is_guest',
            label: '是否显示',
            element: 'a-switch',
            props: {
                placeholder: '是否显示',
                checkedText: '是',
                uncheckedText: '否',
                defaultValue: true,
            },
        },
    },
    {
        title: '是否评论',
        dataIndex: 'is_comment',
        key: 'is_comment',
        ellipsis: true,
        align: 'center',
        width: 100,
        customRender: (item: any) => {
            return item.text ? '是' : '否'
        },
        formData: {
            name: 'is_comment',
            label: '是否评论',
            element: 'a-switch',
            props: {
                placeholder: '是否评论',
                checkedText: '是',
                uncheckedText: '否',
                defaultValue: true,
            },
        },
    },
    {
        title: '创建时间',
        dataIndex: 'createTime',
        key: 'createTime',
        ellipsis: true,
        align: 'center',
        width: 100,
        formData: {
            name: 'createTime',
            label: '创建时间',
            element: 'a-date-picker',
            props: {
                valueFormat: 'YYYY-MM-DD HH:mm:ss',
                placeholder: '选择时间',
                showTime: true,
                type: 'date',
            },
        },
    },
    {
        title: '操作',
        key: 'action',
        align: 'center',
        width: 200,
        slots: { customRender: 'action' },
    },
]
