let tableData = [
    {
        id: 1,
        name: '系统管理',
        icon: 'DiffOutlined',
        updateTime: '2021-10-27 19:55:30',
        router: '',
        viewPath: '',
        keepAlive: '',
        limits: ['admin', 'edit'],
        filePath: '',
        type: '',
        children: [
            {
                name: '菜单列表',
                id: 2,
                icon: 'DiffOutlined',
                updateTime: '2021-10-27 19:55:30',
                router: '',
                viewPath: '',
                keepAlive: '',
                limits: ['admin', 'edit'],
                filePath: '',
                type: '',
            },
        ],
    },
    {
        id: 3,
        name: '组件库',
        icon: 'DiffOutlined',
        updateTime: '2021-10-27 19:55:30',
        router: '',
        viewPath: '',
        keepAlive: '',
        limits: ['admin', 'edit'],
        filePath: '',
        type: '',
        children: [
            {
                name: 'Markdown编辑器',
                id: 4,
                icon: 'DiffOutlined',
                updateTime: '2021-10-27 19:55:30',
                router: '',
                viewPath: '',
                keepAlive: '',
                limits: ['admin', 'edit'],
                filePath: '',
                type: '',
            },
            {
                name: '解析Exel',
                id: 5,
                icon: 'DiffOutlined',
                updateTime: '2021-10-27 19:55:30',
                router: '',
                viewPath: '',
                keepAlive: '',
                limits: ['admin', 'edit'],
                filePath: '',
                type: '',
            },
            {
                name: '文件操作',
                id: 6,
                icon: 'DiffOutlined',
                updateTime: '2021-10-27 19:55:30',
                router: '',
                viewPath: '',
                keepAlive: '',
                limits: ['admin', 'edit'],
                filePath: '',
                type: '',
                children: [
                    {
                        name: '图片上传',
                        id: 7,
                        icon: 'DiffOutlined',
                        updateTime: '2021-10-27 19:55:30',
                        router: '',
                        viewPath: '',
                        keepAlive: '',
                        limits: ['admin', 'edit'],
                        filePath: '',
                        type: '',
                    },
                    {
                        name: '文件上传',
                        id: 8,
                        icon: 'DiffOutlined',
                        updateTime: '2021-10-27 19:55:30',
                        router: '',
                        viewPath: '',
                        keepAlive: '',
                        limits: ['admin', 'edit'],
                        filePath: '',
                        type: '',
                    }
                ]
            },
        ],
    },
];

export default tableData;