export default [
    {
        title: 'ID',
        dataIndex: 'id',
        key: 'id',
        ellipsis: true,
        align: 'center',
        width: 80,
    },
    {
        title: '应用标题',
        dataIndex: 'title',
        ellipsis: true,
        align: 'center',
        curd: {
            el: 'a-input',
            $formItemAttrs: {
                autoLink: false,
                label: '应用标题',
                name: 'title',
                rules: [{ required: true, message: '应用标题为必填项', trigger: 'blur' }],
            },
            $elAttrs: { placeholder: '输入应用标题', value: '' },
        },
    },
    {
        title: '用户ID',
        dataIndex: 'user_id',
        align: 'center',
        ellipsis: true,
        curd: {
            el: 'a-select',
            $formItemAttrs: {
                autoLink: false,
                label: '节点类型',
                name: 'user_id',
            },
            $elAttrs: {
                placeholder: '选择用户',
                value: '',
                options: [],
            },
        },
    },
    {
        title: '标题样式',
        dataIndex: 'title_style',
        ellipsis: true,
        align: 'center',
        visible: false,
        curd: {
            el: 'a-textarea',
            $formItemAttrs: {
                autoLink: false,
                label: '标题样式',
                name: 'title_style',
            },
            $elAttrs: { placeholder: '输入标题样式', value: '', maxlength: 300 },
        },
    },
    {
        title: '栏目类型',
        dataIndex: 'channel_id',
        ellipsis: true,
        align: 'center',
        curd: {
            el: 'a-select',
            $formItemAttrs: {
                autoLink: false,
                label: '栏目类型',
                name: 'channel_id',
            },
            $elAttrs: {
                placeholder: '栏目类型',
                value: '',
                options: [],
            },
        },
    },
    {
        title: '图片',
        dataIndex: 'image',
        ellipsis: true,
        align: 'center',
        curd: {
            el: 'bag-upload-image',
            $formItemAttrs: {
                autoLink: false,
                label: '图片地址',
                name: 'image',
                rules: [{ required: true, message: '图片地址必填项', trigger: 'blur' }],
            },
            $elAttrs: {
                placeholder: '输入图片地址',
                value: '',
            },
        },
    },
    {
        title: '描述',
        dataIndex: 'describe',
        ellipsis: true,
        align: 'center',
        curd: {
            el: 'a-textarea',
            $formItemAttrs: {
                autoLink: false,
                label: '描述',
                name: 'describe',
            },
            $elAttrs: { placeholder: '描述', value: '', maxlength: 300 },
        },
    },
    {
        title: '内容',
        dataIndex: 'content',
        ellipsis: true,
        align: 'left',
        visible: false,
        curd: {
            el: 'md-editor',
            $formItemAttrs: {
                autoLink: false,
                label: '内容',
                name: 'content',
                labelCol: { span: 1, offset: 0 },
                wrapperCol: { span: 22, offset: 0 },
            },
            slot: {
                name: 'curdPname',
            },
            $elAttrs: { placeholder: '输入内容', value: '' },
            $colAttrs: {
                xs: 24,
                sm: 24,
                md: 24,
                lg: 24,
                xl: 24,
            },
        },
    },
    {
        title: '下载地址',
        dataIndex: 'download_site',
        ellipsis: true,
        align: 'center',
        width: 100,
        visible: false,
        curd: {
            el: '',
            $formItemAttrs: {
                autoLink: false,
                label: '下载地址',
                name: 'download_site',
                labelCol: { span: 1, offset: 0 },
                wrapperCol: { span: 22, offset: 0 },
            },
            slot: {
                name: 'BagDownloadSite',
            },
            $elAttrs: { placeholder: '输入下载地址', value: '' },
            $colAttrs: {
                xs: 24,
                sm: 24,
                md: 24,
                lg: 24,
                xl: 24,
            },
        },
    },
    {
        title: '热度',
        dataIndex: 'flag',
        ellipsis: true,
        align: 'center',
        width: 100,
        curd: {
            el: 'a-select',
            $formItemAttrs: {
                autoLink: false,
                label: '热度',
                name: 'flag',
            },
            $elAttrs: {
                placeholder: '选择热度',
                value: '推荐',
                options: [
                    { label: '置顶', value: '置顶' }, { label: '最新', value: '最新' },
                    { label: '推荐', value: '推荐' }, { label: '热门', value: '热门' },
                ],
            },
        },
    },
    {
        title: '选择发布时间',
        dataIndex: 'createTime',
        ellipsis: true,
        align: 'center',
        width: 100,
        curd: {
            el: 'a-date-picker',
            $formItemAttrs: {
                autoLink: false,
                label: '发布时间',
                name: 'createTime',
            },
            $elAttrs: {
                valueFormat: 'YYYY-MM-DD HH:mm:ss',
                placeholder: '选择发布时间',
                showTime: true,
                type: 'date',
                value: '',
            },
        },
    },
    {
        title: '浏览次数',
        dataIndex: 'views',
        ellipsis: true,
        align: 'center',
        width: 100,
        curd: {
            el: 'a-input',
            $formItemAttrs: {
                autoLink: false,
                label: '浏览次数',
                name: 'views',
            },
            $elAttrs: { placeholder: '输入浏览次数', value: '' },
        },
    },
    {
        title: '点赞次数',
        dataIndex: 'likes',
        ellipsis: true,
        align: 'center',
        width: 100,
        visible: false,
        curd: {
            el: 'a-input',
            $formItemAttrs: {
                autoLink: false,
                label: '点赞次数',
                name: 'likes',
            },
            $elAttrs: { placeholder: '输入点赞次数', value: '' },
        },
    },
    {
        title: '点踩次数',
        dataIndex: 'dislikes',
        ellipsis: true,
        align: 'center',
        width: 100,
        visible: false,
        curd: {
            el: 'a-input',
            $formItemAttrs: {
                label: '点踩次数',
                name: 'dislikes',
            },
            $elAttrs: { placeholder: '输入点踩次数', value: '' },
        },
    },
    {
        title: '评论数量',
        dataIndex: 'comments',
        ellipsis: true,
        align: 'center',
        width: 100,
        visible: false,
        curd: {
            el: 'a-input',
            $formItemAttrs: {
                label: '评论数量',
                name: 'comments',
            },
            $elAttrs: { placeholder: '输入评论数量', value: '' },
        },
    },
    {
        title: '游客访问',
        dataIndex: 'is_guest',
        ellipsis: true,
        align: 'center',
        width: 100,
        visible: false,
        customRender: (item: any) => {
            return item.text ? '是' : '否'
        },
        curd: {
            el: 'a-switch',
            $formItemAttrs: {
                autoLink: false,
                label: '游客访问',
                name: 'is_guest',
            },
            $elAttrs: {
                checkedText: '是',
                uncheckedText: '否',
                checked: true,
            },
        },
    },
    {
        title: '是否评论',
        dataIndex: 'is_comment',
        ellipsis: true,
        align: 'center',
        width: 100,
        visible: false,
        curd: {
            el: 'a-switch',
            $formItemAttrs: {
                autoLink: false,
                label: '是否评论',
                name: 'is_comment',
            },
            $elAttrs: {
                checkedText: '是',
                uncheckedText: '否',
                checked: true,
            },
        },
    },
    {
        title: '创建时间',
        dataIndex: 'createTime',
        key: 'createTime',
        align: 'center',
        ellipsis: true,
        width: 200,
    },
    {
        title: '操作',
        key: 'action',
        align: 'center',
        width: 200,
        slot: { name: 'action' },
    },
]
