import {MenuUnfoldOutlined} from "@vicons/antd"
import {UserCircleRegular} from "@vicons/fa";
import {
    ChevronBackOutline,
    ChevronForward,
    HappyOutline,
    Expand,
    SyncOutline,
    PowerOutline,
    ArrowBackOutline,
    ArrowForward,
    Resize,
    LeafOutline,
    CloseOutline,
    HomeOutline,
    MoonOutline,
    SunnyOutline,
    LogoPinterest,
    LogoIonic,
    ColorPaletteOutline,
    Moon,
    Sunny,
    CheckboxOutline,
    GridOutline,
    BookOutline,
    PersonOutline,
    WineOutline,
    NotificationsOutline,
    SettingsOutline,
    Apps,
    Language
} from "@vicons/ionicons5"

export {
    MenuUnfoldOutlined,
    UserCircleRegular,
    HomeOutline,
    ChevronBackOutline,
    ChevronForward,
    HappyOutline,
    Expand,
    SyncOutline,
    PowerOutline,
    ArrowBackOutline,
    ArrowForward,
    Resize,
    LeafOutline,
    CloseOutline,
    MoonOutline,
    SunnyOutline,
    LogoPinterest,
    LogoIonic,
    ColorPaletteOutline,
    Moon,
    Sunny,
    CheckboxOutline,
    GridOutline,
    BookOutline,
    PersonOutline,
    WineOutline,
    NotificationsOutline,
    SettingsOutline,
    Apps,
    Language
}
