export default [
    {
        id: 10001,
        name: 'Test1',
        role: 'Develop',
        sex: '0',
        age: 28,
        address: 'vxe-table 从入门到放弃',
    },
    {
        id: 10002,
        name: 'Test2',
        role: 'Test',
        sex: '1',
        age: 22,
        address: 'Guangzhou',
    },
    {
        id: 10003,
        name: 'Test3',
        role: 'PM',
        sex: '0',
        age: 32,
        address: 'Shanghai',
    },
    {
        id: 10004,
        name: 'Test4',
        role: 'Designer',
        sex: '1',
        age: 23,
        address: 'vxe-table 从入门到放弃',
    },
    {
        id: 10005,
        name: 'Test5',
        role: 'Develop',
        sex: '1',
        age: 30,
        address: 'Shanghai',
    },
    {
        id: 10006,
        name: 'Test6',
        role: 'Designer',
        sex: '1',
        age: 21,
        address: 'vxe-table 从入门到放弃',
    },
    {
        id: 10007,
        name: 'Test7',
        role: 'Test',
        sex: '0',
        age: 29,
        address: 'vxe-table 从入门到放弃',
    },
    {
        id: 10008,
        name: 'Test8',
        role: 'Develop',
        sex: '0',
        age: 35,
        address: 'vxe-table 从入门到放弃',
    },
    {
        id: 10009,
        name: 'Test9',
        role: 'Test',
        sex: '1',
        age: 21,
        address: 'vxe-table 从入门到放弃',
    },
    {
        id: 10010,
        name: 'Test10',
        role: 'Develop',
        sex: '0',
        age: 28,
        address: 'vxe-table 从入门到放弃',
    },
    {
        id: 10011,
        name: 'Test11',
        role: 'Test',
        sex: '0',
        age: 29,
        address: 'vxe-table 从入门到放弃',
    },
    {
        id: 10012,
        name: 'Test12',
        role: 'Develop',
        sex: '1',
        age: 27,
        address: 'vxe-table 从入门到放弃',
    },
    {
        id: 10013,
        name: 'Test13',
        role: 'Test',
        sex: '0',
        age: 24,
        address: 'vxe-table 从入门到放弃',
    },
    {
        id: 10014,
        name: 'Test14',
        role: 'Develop',
        sex: '1',
        age: 34,
        address: 'vxe-table 从入门到放弃',
    },
    {
        id: 10015,
        name: 'Test15',
        role: 'Test',
        sex: '1',
        age: 21,
        address: 'vxe-table 从入门到放弃',
    },
    {
        id: 10016,
        name: 'Test16',
        role: 'Develop',
        sex: '0',
        age: 20,
        address: 'vxe-table 从入门到放弃',
    },
    {
        id: 10017,
        name: 'Test17',
        role: 'Test',
        sex: '1',
        age: 31,
        address: 'vxe-table 从入门到放弃',
    },
    {
        id: 10018,
        name: 'Test18',
        role: 'Develop',
        sex: '0',
        age: 32,
        address: 'vxe-table 从入门到放弃',
    },
    {
        id: 10019,
        name: 'Test19',
        role: 'Test',
        sex: '1',
        age: 37,
        address: 'vxe-table 从入门到放弃',
    },
    {
        id: 10020,
        name: 'Test20',
        role: 'Develop',
        sex: '1',
        age: 41,
        address: 'vxe-table 从入门到放弃',
    },
]